### ISSUE TITLE
Transcribe_PostProcessing failing

### ISSUE THREAD

**Issue by annsarapaul** [TurnTheBusVideo/video_upload_backend#2]
https://ap-south-1.console.aws.amazon.com/cloudwatch/home?region=ap-south-1#logEventViewer:group=/aws/lambda/VideoTranscription_PostProcessing;stream=2020/04/20/%5B$LATEST%5D06fba134cf5b4a6da461ba5791d5b815

April 20, 2020

[ERROR] KeyError: 'end_time'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 38, in lambda_handler
    comment = process_file(TRS_FILE_KEY, SRT_FILE_KEY, BUCKET_NAME)
  File "/var/task/lambda_function.py", line 217, in process_file
    generate_srt_file(srt_file, transcript_file_streaming_body, bucket_name)
  File "/var/task/lambda_function.py", line 109, in generate_srt_file
    srt_content = generate_srt(transcript_file_streaming_body)
  File "/var/task/lambda_function.py", line 100, in generate_srt
    srt_content = generate_srt_from_phrases(phrases)
  File "/var/task/lambda_function.py", line 193, in generate_srt_from_phrases
    tokens.append(phrase["start_time"] + " --> " + phrase["end_time"])

**Comment by annsarapaul** [comment]
Fixed the issue. Had an edge case where the phrase only had one word (pronounciation)
Current phrases are terminated by 10 words or by a punctuation. So if there are 11 words, first 10 made it phrase 1 . But phrase 2 only had one word and end time was not recorded for edge case
